version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./ci/app.dockerfile
    image: yusufcemalcelebi/messaging
    container_name: messaging
    ports:
      - "5000:5000"
    depends_on:
      - mssql
      - mountebank
      - sqlapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
      
  mssql:
    build:
      context: ci
      dockerfile: mssql.dockerfile
    image: yusufcemalcelebi/mssql
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Mypassword!1"
      ACCEPT_EULA: "Y"
  
  mountebank:
    build:
      context: ci
      dockerfile: Dockerfile.mountebank
    container_name: mountebank
    image: cs-mountebank
    ports:
      - "5025:5025"
      
  sqlapi:
    container_name: sqlapi
    image: techciceksepeti/sqlapi:1.6
    ports:
      - "8033:8033"
  # wait-for-it:
  #   image: tutum/curl:alpine
  #   restart: on-failure
  #   command: sh -c "timeout -t 30 sh -c 'until curl -f -s -o /dev/null http://app:5000/healthcheck; do sleep 1; done'"